# Site metadata.

# Canonical URL
url: https://pulse.cio.gov

name: Pulse
title: "The pulse of the federal .gov space"
description: "How federal government domains are meeting best practices on the web."

# Data sources. These URLs should have their content updated in-place.
data:
  # URL where we download the .gov domain list from.
  domains_url: "https://www.dropbox.com/s/368prpwbg9cbgas/domains__current-federal_mos.csv?dl=1"

  # URL where we download the participating DAP .gov list from.
  analytics_url: "https://www.dropbox.com/s/4e0uui88ba7keuj/analytics__second-level-domains_mos.csv?dl=1"

  # DAP URL where we source public .gov subdomains from.
  analytics_subdomains_url: "https://www.dropbox.com/s/mlgnnzioy37qzgg/analytics_subdomains__sites_mos.csv?dl=1"
